#ifndef HYPERSPACE_NAVIGATOR_VERSION_HPP
#define HYPERSPACE_NAVIGATOR_VERSION_HPP

#pragma once

/// The major version number
#define HYPERSPACE_NAVIGATOR_VERSION_MAJOR 1

/// The minor version number
#define HYPERSPACE_NAVIGATOR_VERSION_MINOR 0

/// The patch number
#define HYPERSPACE_NAVIGATOR_VERSION_PATCH 0

/// The complete version number
#define HYPERSPACE_NAVIGATOR_VERSION_CODE (HYPERSPACE_NAVIGATOR_VERSION_MAJOR * 10000 + HYPERSPACE_NAVIGATOR_VERSION_MINOR * 100 + HYPERSPACE_NAVIGATOR_VERSION_PATCH)

/// Version number as string
#define HYPERSPACE_NAVIGATOR_VERSION_STRING "1.0.0"

#endif
